name: Publish release

permissions:
  contents: write # for uploading release artifacts

on:
  workflow_dispatch:
    inputs:
      langserver:
        description: 'The terraform-ls version to use. If not specified will use version in package.json'
        required: false
        type: string
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          include:
            - vsce_target: win32-x64
              ls_target: windows_amd64
              npm_config_arch: x64
            - vsce_target: win32-ia32
              ls_target: windows_386
              npm_config_arch: ia32
            - vsce_target: win32-arm64
              ls_target: windows_arm64
              npm_config_arch: arm
            - vsce_target: linux-x64
              ls_target: linux_amd64
              npm_config_arch: x64
            - vsce_target: linux-arm64
              ls_target: linux_arm64
              npm_config_arch: arm64
            - vsce_target: linux-armhf
              ls_target: linux_arm
              npm_config_arch: arm
            - vsce_target: darwin-x64
              ls_target: darwin_amd64
              npm_config_arch: x64
            - vsce_target: darwin-arm64
              ls_target: darwin_arm64
              npm_config_arch: arm64
    steps:
      - uses: jpogran/vscode-terraform/.github/workflows/publish_extension.yml
        with:
          vsce_target: ${{ matrix.vsce_target }}
          ls_target: ${{ matrix.ls_target }}
